"""add order field for elements of known order

Revision ID: 97cc19ef557b
Revises: 744635b7433d
Create Date: 2024-03-15 00:36:24.633908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cc19ef557b'
down_revision: Union[str, None] = '744635b7433d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'order')
    # ### end Alembic commands ###
